---

# system packages

- name: installing system packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ system_packages }}"
  when: system_packages is defined

# app user

- name: creating the {{ app_user }} user
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    createhome: yes
    group: "{{ app_group }}"

# app dirs

- name: creating {{ apps_dir }} directory
  file:
    path: "{{ apps_dir }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: creating app source directory
  file:
    path: "{{ source_dir }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
    group: www-data

# clone project

- name: installing git
  apt:
    name: git
    state: present
  when: gh_repo is defined and gh_key is defined

- name: copying private key to ~/.ssh/id_rsa_{{ app_name }}
  copy:
    src: "{{ gh_key }}"
    dest: "~/.ssh/id_rsa_{{ app_name }}"
    mode: 0400
  when: gh_repo is defined and gh_key is defined

- name: cloning project into {{ source_dir }}
  git:
    repo: "git@github.com:{{ gh_repo }}"
    dest: "{{ source_dir }}"
    accept_hostkey: yes
    key_file: "~/.ssh/id_rsa_{{ app_name }}"
    update: yes
  when: gh_repo is defined and gh_key is defined

- name: destroying private key
  file:
    path: "~/.ssh/id_rsa_{{ app_name }}"
    state: absent
  when: gh_repo is defined and gh_key is defined

# chown app code

- name: chowning app code
  file:
    path: "{{ source_dir }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: "{{ app_user }}"
    group: www-data

# setup virtualenv

- name: creating virtualenv directory
  file:
    path: "{{ virtualenv_dir }}"
    state: directory
    mode: 0755
    owner: "{{ app_user }}"
    group: www-data

- name: creating virtualenv
  command: virtualenv -p python{{ python_version }} {{ virtualenv_dir }} creates="{{ virtualenv_dir }}/bin/activate"
  when: python_version >= 3

- name: creating virtualenv
  command: virtualenv {{ virtualenv_dir }} creates="{{ virtualenv_dir }}/bin/activate"
  when: python_version < 3

- name: chowning virtualenv
  file:
    path: "{{ virtualenv_dir }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: "{{ app_user }}"
    group: www-data

# pip install stuff

- name: pip installing python packages
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ virtualenv_dir }}"
    chdir: "{{ source_dir }}"
  with_items: "{{ python_packages }}"
  when: python_packages is defined

- name: pip installing requirements
  pip:
    requirements: "{{ requirements_file }}"
    virtualenv: "{{ virtualenv_dir }}"
    chdir: "{{ source_dir }}"
  when: requirements_file is defined

# vassal ini

- name: creating vassal ini file
  template:
    src: vassal.ini.j2
    dest: /etc/uwsgi-emperor/vassals/{{ app_name }}.ini
    owner: "{{ app_user }}"
    group: www-data
  when: app_enabled
  notify: restart uwsgi

- name: making sure uwsgi is running
  service:
    name: uwsgi-emperor
    state: restarted
